_config.yml, _includes/_author-bio.html
sina weibo is a widely-used social community in China
=> add social button in author-bio.html

_docs/15-stylesheets.md
Line 164: added missing `run` part of the nam command.
=> incorrect npm command

_docs/05-configuration.md
Changed a you to your on line 286
I'm not really sure why it says I changed line 531...I didn't and there's no difference.
=> Fix typo in 05-configuration.md

_data/ui-text.yml
=> Added spanish locale on ui-text.yml

_includes/seo.html
=> Fix branch logic for Yandex and Alexa. Closes #347

_data/ui-text.yml
=> Update ui-text.yml to add "tr" locale

_config.yml, _includes/footer.html
Solution for #378 based on the discussions in #379 .
=> Add external atom feed URL config possibility

_data/ui-text.yml
I'm from Brasil and added the Portuguese to ui-text file
=>  Adding Portugese in the ui-text

_includes/seo.html
Addresses issue #462 
See http://fbdevwiki.com/wiki/Locales
=> formats og:locale tag with underscores

_data/ui-text.yml
Thanks for this nice template. Here is my little contribution.
=> Completed Italian translation

_data/ui-text.yml
updated Portuguese translation
=> update Portuguese translation

_docs/09-layouts.md
Was "none", should be "known".
=> Swapped a word

_data/ui-text.yml
Hi @mmistakes 
I created a german translation for the ui-text's. I'll send over the docs pull request right after.
Cheers
Roger
=> add german (Deutsch) translation

_includes/seo.html
Adding standard meta description immediately after seo_description has been defined
=> Update seo.html for meta description

_data/ui-text.yml
=> Added missing Turkish translation for UI text

_data/ui-text.yml
- `comment_success_msg` : Just corrected a missing `m` in *commentaire*
- `related_label` : Added `aussi` (*as well*) in the end of the sentence to make it more "natural" French
- `less_than` : `plus petit que` wasn't right in this precise context - this form is more about the mathematical character `<` - `moins de` is one of the exact use in this particular case (talking about duration)                    
*Less than one minute* == `Moins de 1 minute`
- `follow_label` : Using `Contact` in place of `Suivez moi` make it less personal, and so, better suited for most cases (`Suivez moi` is more like `Follow me`)
________________
Anyhow, thank you very much for your hard work
=> Slight corrections/improvments with French

_data/ui-text.yml
=> Nepalese Language

_includes/comments.html
=> Fix bug - include section for Discourse embedded comments

_data/ui-text.yml
Added Traditional Chinese translations for UI text.
=> Added zh-TW translation.

CHANGELOG.md, _sass/_page.scss, _sass/_print.scss, docs/_docs/18-history.md, docs/_sass/_page.scss, docs/_sass/_print.scss
=> Improve print styles

_data/ui-text.yml
Awesome project, I really love your work!
It seems, that one of the greatest languages/locales has not been added yet to the project - Lithuanian. This PR does that.
This translation already works on top of your work: https://www.jarmalavicius.lt/
Feel free to ping me if there are changes in translation in the future.
=> PR: Add Lithuanian language/locale

docs/_docs/05-configuration.md
=> Fixed link errors in docs

_data/ui-text.yml
Translated this for my page today https://github.com/ojn/www.netkom.se/blob/master/_data/ui-text.yml
I hope there are no spelling mistakes, since one should strive for "minimal mistakes"... :-)
=> Add Swedish language

_sass/minimal-mistakes/_utilities.scss, _sass/minimal-mistakes/_variables.scss, docs/_sass/minimal-mistakes/_utilities.scss, docs/_sass/minimal-mistakes/_variables.scss
Add a new brand variable `$bitbucket-color: #205081` for the social icon.
=> Bitbucket social icon color

_docs/02-structure.md
Previous wrong name was `navigations.yml`
=> Mistake on file navigation.yml

docs/_pages/about.md
=> HTTPS some external links

_includes/comments-providers/scripts.html, _includes/comments.html
Addresses issue #1092 where google plus comments section was stuck on loading/opening
=> Google+ page comments updated.

_data/ui-text.yml
=> Spanish text for comments

_data/ui-text.yml
I added support for vietnamese to ui-text.yml file
=> Support Vietnamese

README.md
I added the extension file name in order to make it work.
=> License url fixed in README file

_data/ui-text.yml
The original translation is incorrect.
=> Update Chinese translation for date_label.

docs/_docs/16-stylesheets.md
=> Update font stack documentation

_data/ui-text.yml
Adding polish locale to ui-text.yml
=> Polish locale

_includes/author-profile.html
Fix the spelling of some product names in the author profile.
=> Fix author profile link texts

_includes/analytics.html
=> Remove analytics in dev environment

_layouts/single.html
=> Remove comments in dev environment

LICENSE.txt
Simple grammar mistake. Yes, i took the time to read this haha
=> Capitalised the name "tracy tram" > "Tracy Tram"

docs/_pages/archive-layout-with-content.md, docs/_posts/2013-01-11-markup-html-tags-and-formatting.md, test/_pages/archive-layout-with-content.md, test/_posts/2013-01-11-markup-html-tags-and-formatting.md
E=mc2 is usually attributed to Albert Einstein.
This is Just a little fix. Hope it can help.
=> Fix docs. Change Isaac Newton with Albert Einstein

_includes/scripts.html
Update Font Awesome to latest version
=> Update Font Awesome to latest version (v5.0.6)

_includes/scripts.html
REF: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md
=> Update Font Awesome JS to 5.0.7

_includes/scripts.html
REF: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md
=> Update Font Awesome JS to 5.0.8

_includes/scripts.html
REF: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md
=> Update Font Awesome

_config.yml, _includes/analytics-providers/google-gtag.html, _includes/analytics-providers/google-universal.html, _includes/analytics-providers/google.html
Hey,
I would like to anonymize the analytics ip address.
Since I didn't find any option to do it, I created it.
Let me know if more changes are required.
Thanks
=> Add option to anonymize analytics ip address

docs/_docs/10-layouts.md
=> Update example Reddit social share interpolation syntax

_includes/scripts.html
REF: https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md
=> update Font Awesome to v5.0.13

_includes/seo.html
naver-site-verification to naver_site_verification
=> Fix typo in seo template

_data/ui-text.yml
This pull request simply adds a couple of translations in french.
=> Add french translations

_includes/masthead.html
=> Fix: use relative links for menu items when possible

docs/_pages/404.md
=> Always load Google 404 Linkhelp script over HTTPS

_includes/head.html
=> Remove unneeded HandheldFriendly and MobileOptimized meta tags

assets/js/lunr/lunr-store.js
=> Fix Lunr search index merging words

CHANGELOG.md, _sass/minimal-mistakes/_archive.scss, _sass/minimal-mistakes/_search.scss, _sass/minimal-mistakes/skins/_dark.scss, _sass/minimal-mistakes/skins/_neon.scss, _sass/minimal-mistakes/skins/_plum.scss, docs/_docs/18-history.md, test/_posts/2016-02-24-welcome-to-jekyll.md
Fixes positioning of nested archive item links.
See #1903
=> Fix Algolia search link positioning

README.md, _data/ui-text.yml, docs/_pages/about.md
Add translation for ui-text in Hindi.
Fixes #1887
=> Hindi Translation of ui-text #1887

_includes/author-profile.html
As suggested by @mmistakes in https://github.com/mmistakes/minimal-mistakes/issues/1948#issuecomment-439888193
Added missing ref attribute
https://github.com/mmistakes/minimal-mistakes/issues/1948
=> Added missing ref attribute

_includes/video
Add Google Drive as video provider
No
=> Add Google Drive as video provider

_includes/scripts.html
REF: fontawesome.com/changelog/latest
=> Update Font Awesome to 5.6.0

_includes/comments-providers/staticman.html, _includes/comments-providers/staticman_v2.html
The title says it all.
The removed variable is *never* used in the script.
=> Remove unused JavaScript variables

docs/_docs/05-configuration.md
- Corrected Staticman v3 URL scheme in the documentation introduced by #1956
- Improved the instructions by providing sample config parameters
I apologize again for the confusion.  Related: #2034
=> Improve Staticman v3 documentation

_data/ui-text.yml
- search_placeholder_text
- results_found
- back_to_top
=> Add missing Chinese text strings

docs/_docs/14-helpers.md
=> Add tip on how to start a YouTube embed at a given timestamp

_includes/analytics-providers/google-universal.html
This is an enhancement
Updated the Google Analytics Universal snippet - less code and faster async loading. As recommended by [HTML5Boilerplate](https://github.com/h5bp/html5-boilerplate/blob/master/src/index.html)
It's an official implementation and posted on the Analytics Developer site: https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet
=> update Google Universal Analytics to load async

_data/ui-text.yml
French translation for `results_found` key was incorrect ("Aucun résultat trouvé" means "No result found").
N/A
=> Fix french translation typo

_data/ui-text.yml
Updated vi-VN locale for some missing terms.
```yml
search_placeholder_text    : "Nhập từ khóa cần tìm..."
results_found              : "Kết quả tìm được"
back_to_top                : "Về đầu trang"
```
=> Updated vi-VN for some missing terms

_data/ui-text.yml
I just fixed some typos PT-BR, included translations for words that were not translated and changed some words to better describe the tag's meaning. This is how I use it in my Portuguese blog.
=> Typos fix and including more words for pt-br

_data/ui-text.yml
Due to unknown reason, Hindi translation of ui-text was missing (https://github.com/mmistakes/minimal-mistakes/issues/2101)
I have added it back from a previous pull request (https://github.com/mmistakes/minimal-mistakes/pull/1888)
=> Added missing Hindi Translation of ui-text

docs/_data/ui-text.yml
Due to unknown reason, Hindi translation of ui-text was missing (https://github.com/mmistakes/minimal-mistakes/issues/2101)
I have added it back from a previous pull request (https://github.com/mmistakes/minimal-mistakes/pull/1888)
=>  Added missing Hindi Translation of ui-text ( for docs folder)

_data/ui-text.yml
I am using this theme on [my personal blog ](www.samiti.me) and i translated the UI text  from English into Thai Language.
=> Add Thai Language For UI Text

docs/_config.yml
=> add www to facebook.com link

_data/ui-text.yml
This fixes some issues with the Spanish localization of Minimal Mistakes and also adds missing strings.
=> Fix and complete Spanish localization

_data/ui-text.yml
This is an improvement on the existing pt-BR (Brazilian Portuguese) localization. Some strings were changed to correct for grammar and for better readability/consistency, and one additional string was translated.
=> Fix and improve pt-BR localization.

_data/ui-text.yml
Update for the localized text strings for `Punjabi` and `Hindi` language
=> Updated localized text string for "Punjabi" and "Hindi" language

_includes/seo.html
SEO now shows author tag properly
=> Fix default site.author in seo.html

_data/ui-text.yml
This adds missing strings to the Spanish localization of Minimal Mistakes
=> Complete Spanish localization

_config.yml
There have been missing closing tags in a comment in the config file, which triggered my 'inner autism'.
This is not related to any issue.
=> Fix typo in config comment

CHANGELOG.md, README.md, _layouts/default.html, _sass/minimal-mistakes.scss, assets/js/main.min.js, docs/_docs/01-quick-start-guide.md, docs/_docs/04-upgrading.md, docs/_docs/18-history.md, docs/_layouts/default.html, docs/_pages/home.md, minimal-mistakes-jekyll.gemspec, package-lock.json, package.json
- Update Chinese (Simplified) localized UI text strings. [#2286]
- Update list of 3rd party JavaScript used and licenses. [#2276]
- Fix indention of nested GFM task lists. [#2283]
=> Release 4.17.1 💎

.gitignore, _config.yml
Probably a harmless fix but a nail in the eyes of perfectionists.
=> Fix typo in comments in _config.yml

_data/ui-text.yml
Add missing dutch ui-text fields
Not related to an open issue
=> Add missing dutch ui-text fields

_includes/seo.html
=> Fixed page.excerpt to seo_description

_sass/minimal-mistakes/_archive.scss
=> Make feature row live well with TOC, fix #2327

_data/ui-text.yml
This pull request adds an Irish language locale to ui-text.yml
=> Add Irish (Gaeilge) locale to ui-text.yml

_includes/page__hero.html
=> fixed typo in  page_hero

docs/_docs/05-configuration.md
update links to HTTPS and remove Google+ from 05-configuration.md
=> update links to HTTPS and remove Google+ from 05-configuration.md

_data/ui-text.yml
Initial Finnish translations for this great theme :) Thanks!
=> Finnish translations

docs/_docs/05-configuration.md
This is a documentation change. 
`https://github.io.mmistakes` should be `https://mmistakes.github.io`
=> Fix typo in configuration docs

_data/ui-text.yml
=> Update Burmese translation

_includes/page__date.html, _layouts/single.html
This pull requests makes it easier to make your own logic about when and how to show the date without having to modify the layout file.
E.g. I want to not show the date on old post, and this makes it possible to do that only changing the included file with the date logic.
=> Move page date Liquid to include

_includes/author-profile.html
=> Add `relative_url` filter to author home link

CHANGELOG.md, _data/ui-text.yml, docs/_docs/18-history.md
I was trying to build a Chinese website and found some translation suboptimal (I'm a native speaker). Also filled in some missing fields for Traditional Chinese.
=> Update UI text for zh-CN and zh-TW

_layouts/posts.html
=> Remove hidden posts from posts.html layout

_includes/seo.html
Add article:author which is used by Pinterest in the SEO-portion of the site.
=> Added article:author used by Pinterest

_data/ui-text.yml, docs/_docs/08-ui-text.md
This is a documentation change. 
Translation of ui-text into Norwegian, added to list of  translations in the documentation.
=> Norwegian translation

_data/ui-text.yml
Update translation for Vietnamese
=> Update ui-text.yml for Vietnamese

_data/ui-text.yml
Add hebrew translation to the ui-text.yml
This is related to the fact that I just started using "minimal mistakes" theme on my Hebrew blog.
=> Add hebrew translation

README.md
=> Update README text for Gumshoejs license

_includes/search/search_form.html
Adding aria landmark to the search forms.
=> Add role to search forms

_data/ui-text.yml
=> Added Danish translations

_includes/author-profile.html
Previously there was a sameAs prop to the author links. This commit restores it if it is a link.
=> Added sameAs to author links

_layouts/single.html
Makes it possible to enable breadcrumbs on a per page basis. That will make it possible to disable breadcrumbs for an entire colletion alos by only editing the _config.yml.
=> Make it possible to enable breadcrumbs per page

docs/_docs/16-stylesheets.md
I fixed a minor grammar mistake I found while browsing the docs.
=> Fixed a grammar mistake.

_data/ui-text.yml
Add Ukrainian translation for UI
=> add Ukrainian UI

_includes/schema.html, _includes/seo.html, schema.html
By moving the schema to it's own file it is easier to change it to your likings without having to edit the seo.html.
The schema markup plays a bigger and bigger role for Google, it seems, and this change will make it easier to improve the Schema implemented. And Google prefers the JSON-implementation.
I can make a follow up pull request to make a better out-of-the-box Schema-implementation with JSON, if improvements here would be considered?
This is not related to any current open Github issue.
=> Make changes to schema easier

_includes/footer.html
ahrefs is warning about this since the link redirects to the new path
=> Change the link it is redirecting to - Fix ahref issue

_data/ui-text.yml
Add missing Polish translation.
=> Add missing Polish translation

_includes/social-share.html, _sass/minimal-mistakes/_buttons.scss, _sass/minimal-mistakes/_variables.scss
This adds a "Share on Bluesky" button, following the pattern for the existing buttons for twitter, facebook, etc.
Screenshot:
=> Add a "Share on Bluesky" button

CHANGELOG.md, _includes/footer.html, _includes/masthead.html, _includes/seo.html
Add HTML escaping for some titles, labels and metada that was missing.
n/a
=> additional HTML escaping for titles and metadata
