- _includes/_open-graph.html
facebook meta tag image sharing added in the_open-graph.html realted to #149 issue. While sharing posts or page using facebook shar its not picking the rite image. Now its corrected adding ioen graph image tag added.
> facebook sharing image meta tag added related #149 issue

- _config.yml
- _includes/_author-bio.html
I wanted to include CodePen on my site, and since there's already a [FontAwesome icon for it](http://fortawesome.github.io/Font-Awesome/icon/codepen/), seemed like an easy addition that I thought others could benefit from.
> Add CodePen to owner social options

- _includes/_disqus_comments.html
This also fixes an issue during page load with Disqus comments on them, `comments powered by Disqus` displayed then got pushed down.
> Removed duplicate 'powered by Disqus'

- theme-setup/index.md
Minor correction to `bundle exec` command.
> Fix typo in `bundle exec` command

- _includes/_navigation.html
Remove unnecessary role element.
See:
http://stackoverflow.com/questions/31831214/bootstrap-html-validator-warning-element-nav-does-not-need-a-role-attribute
https://validator.w3.org/nu/?doc=https%3A%2F%2Fmmistakes.github.io%2Fminimal-mistakes%2F
> Remove navigation role as it is unnecessary

- package.json
The script "build:all" was missing the "npm run" section for the "build:js" part.
> Fix "build:all" npm script

- _includes/page__hero.html
The `overlay_filter` param lets you darken or otherwise filter the hero header picture to make the text content pop out more.
You can use it by specifying the opacity (between 0 and 1) of a black overlay like so:
```yaml
excerpt: "This post should [...]"
header:
overlay_image: unsplash-image-1.jpg
overlay_filter: 0.5 # same as adding an opacity of 0.5 to a black background
caption: "Photo credit: [**Unsplash**](https://unsplash.com)"
cta_label: "More Info"
cta_url: "https://unsplash.com"
```
Or if you want to do more fancy things, go full rgba: 
```yaml
excerpt: "This post should [...]"
header:
overlay_image: unsplash-image-1.jpg
overlay_filter: rgba(255, 0, 0, 0.5)
caption: "Photo credit: [**Unsplash**](https://unsplash.com)"
cta_label: "More Info"
cta_url: "https://unsplash.com"
```
> Add overlay_filter param to hero headers

- _data/ui-text.yml
- index.html
I recently succeed to install and build my site with this theme (I got some issues with osx…). I have noticed that the page title of the index page was not translated.
Let me know if I can make other pull request like this or if it's preferable to "hard translate" in template inside of my project/repository.
Thanks
PS : I also have noticed a "no new line at end of file" diff but I don't know how to fix that. I am with osx and used vim to edit. I hope it's not a problem for you.
> Translate index page title

- _config.yml
- _includes/comments-providers/discourse.html
- _includes/comments-providers/scripts.html
The comment system can be changed to embed topics from the Discourse
forum software: http://discourse.org/
More details: https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963
> javascript to embed comments from discourse forum

- _includes/seo.html
Add Open Graph Image tag if `page.header.overlay_image` is used. Additionally, fix a casing issue in the theme's generated microdata.
> Open Graph Image Tag for Header Overlay Images

- _includes/author-profile.html
I do not have an authors.yml file and so using this when a post has an author was failing.  Added check to see if there is an author in the data and if not, defaults to author data from _config.yml.
> Updated author-profile.html in the event that there is no authors.yml file

- _includes/seo.html
Use page.header.teaser instead of site.og_image in twitter:image and  og:image meta tags
> Additional options for images to use in social share meta tags

- _layouts/archive.html
- _layouts/single.html
- _layouts/splash.html
> Fix Liquid syntax error for offending parentheses

- _docs/07-ui-text.md
Since there are several translations in the master branch, they should also be featured in the docs.
For further additions I styled them as a list in alphabetical order.
The native language description (e.g. Français) might make it easier to find this page for search queries in the native language. But I'm not sure if it is worth the effort...
> Add list of available translations

- _includes/author-profile.html
The Follow button Label wasn't localized with the ui-text value, now it is with default to "Follow".
The colon from the end of the ui-text value of `follow_label` is being removed by the liquid filter `remove: ":"`
> get Follow-Button label from ui-text and default to "Follow"

- _includes/category-list.html
I noticed that base_path is included twice in category-list.html.
Does not seem to have any reason why it is included twice. 
The second overwrites the first.
> Remove duplicate include of base_path in category-list.html

- _layouts/default.html
Feature enhancement that adds the 2 related capabilities that enable users to:
1. Detect the layout of a page via CSS or JavaScript, and
2. Toggle various user-defined classes in the `body` tag's `class` attribute by assigning an array of classnames to the `page.classes` or `layout.classes` variables. If `page.classes` is defined, overrides `layout.classes`. (I would prefer concatenation, but that doesn't seem to work).
This enables users to specify custom styles to use for specific pages and components on that page. 
For instances, the landing page might have specific styling that is only used on that page.
```yaml
---
layout: splash
classes:
- landing
- dark-theme
---
```
Outputs:
```html
<body class="layout--splash landing dark-theme">
```
> Add classnames to body element

- _includes/author-profile.html
lastfm.com/user... results in a server error, last.fm/user... is the correct URL.
> Fixed Last.fm URL

- _includes/social-share.html
* Include the page title before the URL
* If twitter.username is set, pass the `via` paramter for attribution
> includes: Enhance Twitter share link

- _docs/07-ui-text.md
Hi Michael, here's the Docs addition PR for the follwing two PR's:
* #546 (add german (Deutsch) translation)
* #532 (Add zh-CN)
Thank you and have fun
Roger
> add Chinese and German (Deutsch) to the languages list

- _includes/author-profile.html
Adds schema.org properties for the `itemtype="http://schema.org/Person" ` in the file ['_includes/author-profile.html'](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/author-profile.html). The following properties were added: 
- `image` for `author.avatar`
- `name` for `author.name`
- `description` for `author.bio`
- `homeLocation` (adds a `itemtype="http://schema.org/Place"` with `itemprop="name"` for `author.location` )
- `url` for `author.uri`
- `email` for `author.email`
- `sameAs` for all the social media links
As the schema.org attributes added made the lines of text longer, I also modified some of the indentation so the html source is a bit easier to understand. 
This lets Google's Crawler see all the structured data (this can be tested at using [Google's …
> Add structured data markup for `itemtype="http://schema.org/Person"` in author-profile.html

- _includes/comments-providers/discourse.html
- Changes the link in the Discourse comments template, `<noscript>` section, to point to the Discourse.org homepage instead of a specific instance of Discourse (beta-europe.org).
This has been changed because the original "link" looks like a mistake:
- It does not appear to be related to this project,
- It is in Markdown format - Markdown is not parsed in this `.html` partial, and,
- There is a stray `</a>` tag after it.
> Fix Discourse noscript link

- docs/_docs/05-configuration.md
Fix invalid 'analytics' example
[_includes/analytics-providers/google-universal.html#7](https://github.com/mmistakes/minimal-mistakes/blob/master/_includes/analytics-providers/google-universal.html#L7)
> Edit docs/configuration (fix analytics example)

- _includes/page__hero_video.html
- _includes/responsive_video
- _layouts/single.html
- _sass/_utilities.scss
- docs/_docs/14-helpers.md
- docs/_includes/page__hero_video.html
- docs/_includes/responsive_video
- docs/_layouts/single.html
- docs/_posts/2017-01-23-layout-header-video.md
- docs/_sass/_utilities.scss
Follow-up fixes for #781:
1. Submit pull request against the develop branch and not master. 
2. Fix indenting in (2 space vs. 4)
3. Move inline CSS to Sass partial (_sass/_utlities.scss)
4. Replace apostrophes with double quotes ie: <div class="embed-container"> instead of <div class='embed-container'>
Additional enhancements:
1. Refactored embed video from `_includes/page__hero_video.html` into `_includes/responsive_video`
2. Updated `_includes/page__hero_video.html` to use `{% include responsive_video id="..." provider="..." %}`
3. Updated documentation with 1) blog post for layout with header video, and 2) new "Video" section in the Helpers documentation.
Let me know if there's any further modifications required for merging. Thanks! =)
> Add responsive video header and include with docs

- _includes/analytics-providers/google-universal.html
The google universal analytics embed code looks to be slightly different now, including an https before the url to the analytics script.
> Add https prefix to google-universal embed code.

- docs/_docs/05-configuration.md
- docs/_docs/10-layouts.md
First of all let me thank @mmistakes for helping me out with some issues I had.
I've noticed that the documentation puts some effort initially to help the novice user but on some subjects fails to help out. 
I've documented all my experience [Novice guide for Jekyll on Windows and github pages](https://sarafian.github.io/tips/2017/02/08/Novice-guide-to-run-Jekyll-on-Windows-and-github-pages.html) and I would like to contribute the relevant information.
> Improve the documentation for novice users (Tags+Categories and Pagination)

- _sass/_navigation.scss
> Repair aggressive box-shadow in navigation.

- docs/_config.yml
YAML references are not always obvious, and ensuring people know to remove your Google IDs seemed a good idea to comment on.  Thanks for minimal mistakes!
> Added a few clarifying comments

- _includes/seo.html
I added the meta tag author which was missing.
In case of fallback to site author, seo_author is now assigned to site.author.name instead of site.author[0] which always produced an empty string.
> meta tag "author" added, for site author the field name is used

- _layouts/single.html
- docs/_layouts/single.html
This removes a buggy conditional that checks if `related_label` is
available in translations and prevents header to be displayed in
some edge cases.
Fix #900
> Remove buggy conditional around related posts header

- _includes/video
when served over https the vimeo link was failing. defer scheme used for video iframe src urls
realtive to the current protocol (e.g. http or https)
closes #944
> fix(includes/video): use https always

- _data/ui-text.yml
Hello,i m working on your project and i really love your work,congratulations.It seems that greek language has not been added to the project and this p.r does that!
Thank you.
> add greek language

- _includes/paginator.html
Removing duplicate <a> and <li> closing tags in paginator include.
> Removing extraneous a and li tags

- docs/_docs/05-configuration.md
Configuration docs were pointing to example `_config.yml` on a gh-pages branch which showed Not Found when clicked.
> Fix broken link to example _config.yml file

- _config.yml
- _includes/author-profile.html
- _includes/footer.html
Since gitlab is widely used, add it as an option in site wide configuration and include it in the standard author profile links.
> add gitlab to author profile

- _sass/minimal-mistakes/_footer.scss
- _sass/minimal-mistakes/_masthead.scss
- _sass/minimal-mistakes/_navigation.scss
- _sass/minimal-mistakes/_page.scss
- _sass/minimal-mistakes/_variables.scss
- docs/_sass/minimal-mistakes/_footer.scss
- docs/_sass/minimal-mistakes/_masthead.scss
- docs/_sass/minimal-mistakes/_navigation.scss
- docs/_sass/minimal-mistakes/_page.scss
Addresses #1146 .
Tested locally, everything seemed to work as expected. Let me know if I need to change anything.
> Refactor intro animations into a separate sass variable

- docs/_docs/16-stylesheets.md
Just thought I'd include a section in the docs about it since it's now officially supported and it might be a common enough use case to warrant explanation.
> Include documentation on disabling animations

- _includes/page__hero.html
- docs/_docs/10-layouts.md
This allows specifying a custom alt tag for a header image. Currently the theme defaults to the site title or nothing. I use a screen reader so noticed this right away, and fixed it on my site, so thought I'd push the change. Simply specify the image_description along with the image in the front matter.
> Header alt tags

- CHANGELOG.md
- _sass/minimal-mistakes/_archive.scss
- _sass/minimal-mistakes/_navigation.scss
- _sass/minimal-mistakes/_page.scss
- _sass/minimal-mistakes/_sidebar.scss
- docs/_docs/18-history.md
- docs/_posts/2012-01-03-layout-table-of-contents-bottom-post.md
- docs/_sass/minimal-mistakes/_archive.scss
- docs/_sass/minimal-mistakes/_navigation.scss
- docs/_sass/minimal-mistakes/_page.scss
- docs/_sass/minimal-mistakes/_sidebar.scss
- test/_posts/2012-01-03-layout-table-of-contents-bottom-post.md
- test/_posts/2012-01-03-layout-table-of-contents-post.md
Improve `page` and `archive` layout
- Center main content on page
- Harmonize sidebar columns to be equal widths
Fixes #1155
> Improve `page` and `archive` layouts

- _includes/social-share.html
The links to the various social networks include data from the post
(title and url) which can contain URL special characters.  Pass each of
the generated URLs through Liquid's `url_encode` filter to build HTML
complaint URLs.
> URL Encode Title and Page URL in Social Share Links

- _includes/comments-providers/disqus.html
The old code seems to not be working anymore, the new code is based from Universal Embed Code that Disquss introduced recently.
Source:
https://help.disqus.com/customer/portal/articles/472097-universal-embed-code
> Replace old Disqus script with Universal Embed Code

- docs/_docs/05-configuration.md
Per https://github.com/mmistakes/minimal-mistakes/issues/811
> Docs - Clarify that jekyll-archives has to be installed

- docs/_docs/05-configuration.md
Per https://github.com/mmistakes/minimal-mistakes/issues/811#issuecomment-325778136
> Clarify taxonomy page and index generation

- README.md
- docs/_docs/10-layouts.md
- docs/_docs/14-helpers.md
- docs/_pages/about.md
- docs/_pages/tag-archive.html
- test/_pages/tag-archive.html
More consistent with "Posts by Category"
> Posts by Tag (singular)

- _data/ui-text.yml
Although the original one can be understood, it seems strange for a native Chinese speaker. I think the updated version should be better.
> Improve translation for minute_read.

- docs/_docs/05-configuration.md
I think my previous commit broke it by removing the newline before `{: .notice–warning}`
> Fix kramdown break

- _config.yml
`gems` key in `_config.yml` was deprecated in Jekyll 3.5 and changed to `plugins`.
ref: https://github.com/jekyll/jekyll/pull/5130
> Rename `gems` key to `plugins`

- _data/ui-text.yml
There are some issues in the brazilian portuguese translation:
```  
less_than                  : "meno que" 
```
the word "meno" doesn't exist in the language, the correct translation is "menos"
```
minute_read                : "minutos de leitura" 
```
once we can one or more minutes of reading, the plural of the word "minuto" is optional, so we can use "(s)" after the word "minuto" to reflect this
```
related_label              : "Você Talvez Goste Também" 
```
this change is for better reading, the previous translation is not good
I changed the capitalization of the subsequent words for lowercase to have default capitalization in all translations.
You can see the results of this translation in my personal blog, [pierryangelo.github.io](pierryangelo.github.io)
Thanks.
> Changing translation in pt-br

- _sass/minimal-mistakes/_variables.scss
Use `BlinkMacSystemFont` instead of private font name.
Closes #1289
> Fix system font rendering in Chrome on macOS/OS X

- _config.yml
- _includes/seo.html
I Added a new search engine [Naver](https://naver.com/) to SEO.
Working example is [my github pages](https://lovemewithoutall.github.io/).
> Add naver-site-verification to SEO

- _includes/toc.html
- docs/_includes/toc.html
See https://github.com/allejo/jekyll-toc/issues/4
> Update jekyll-toc with heading classes fix

- _includes/footer.html
GitHub, Gitlab and Bitbucket are all always served over HTTPS.
Facebook links always have www.
> HTTPS links to github, gitblab and bitbucket and add www to facebook

- assets/js/lunr-en.js
Without layout set to null a HTML template will be rendered around the JavaScript, causing an error while loading the file in the browser.
```
lunr-en.js:1 Uncaught SyntaxError: Unexpected token <
```
> Fix lunar-en.js layout (Uncaught SyntaxError)

- docs/_posts/2012-01-03-layout-table-of-contents-post.md
Hey @mmistakes,when i was trying to work with buttons,i found out that the button class needs 2 "--" instead of 1.Keep up the perfect job with the theme,we love it!
> Fix button class

- _includes/masthead.html
- docs/_docs/07-navigation.md
> Tooltips for masthead links

- _data/ui-text.yml
> Point zh-hk to Traditional Chinese

- _includes/author-profile.html
- _sass/minimal-mistakes/_sidebar.scss
- docs/_docs/05-configuration.md
This pull request is an attempt at addressing #1331.  This is the simplest/cleanest way that I can think to add this functionality.  If this is too messy, I completely understand and we can close this and I can simply do it locally, but again, I always like to keep customization as minimal as possible to more easily take advantage of future updates.
At any rate, I think this solution does solve the concern noted in #1331 around easily turning it on/off and allowing it for one, some, or many authors depending on the site's structure.
Basically, the code will check for an `author.linkback` yml key and if it is set, then it will add the link around a given author's avatar and name.  If it is not set, then the link will not be generated.
If this is something you'd consider adding in, I can …
> Feature: Adding linkback functionality Author avatar & Name

- _data/ui-text.yml
I didn't add the translations of "less than" and "minute read" for the following reasons.
- `read_time` does not work in Japanese documents.
- The Japanese translations of "less than" and "minute read" are "未満" and "分" respectively, but the word order is different like "1分未満."
Also, I didn't add the translations of "feed," "powered by," "website" and "email" because the alphabet was more natural.
---
I like this theme very much.  Thank you!
> Add Japanese translation of ui-text

- _includes/page__hero.html
- docs/_docs/10-layouts.md
These two patches introduce a new feature (#1429) allowing the per-page override of whether or not to display the excerpt in the overlay text, and document its usage.
v2:
- Correct typo in documentat (test -> text)
- Explicitly test for "!= false" to avoid changing default behavior
- Remove _config.yml changes as they are no longer needed to maintain default behavior
> v2: Introduce show_overlay_excerpt and document 

- docs/_docs/01-quick-start-guide.md
> docs: Remote plugin reference unnecessary for GitHub Pages

- _sass/minimal-mistakes/_syntax.scss
- _sass/minimal-mistakes/_variables.scss
- _sass/minimal-mistakes/skins/_contrast.scss
- _sass/minimal-mistakes/skins/_dark.scss
- _sass/minimal-mistakes/skins/_dirt.scss
- _sass/minimal-mistakes/skins/_neon.scss
- _sass/minimal-mistakes/skins/_plum.scss
- _sass/minimal-mistakes/skins/_sunrise.scss
- docs/_posts/2013-08-16-markup-syntax-highlighting.md
- test/_posts/2013-08-16-markup-syntax-highlighting.md
To make customizing the colors used in code highlighted blocks, hard-coded values have been replaced with Sass variables. These variables use a base of sixteen colors ([Base16](http://chriskempson.com/projects/base16/)) to style syntax.
Code block colors can easily be changed by overriding any of the following color variables as [noted in the docs](https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/).
```sass
/* syntax highlighting (base16) */
$base00: #263238;
$base01: #2e3c43;
$base02: #314549;
$base03: #546e7a;
$base04: #b2ccd6;
$base05: #eeffff;
$base06: #eeffff;
$base07: #ffffff;
$base08: #f07178;
$base09: #f78c6c;
$base0a: #ffcb6b;
$base0b: #c3e88d;
$base0c: #89ddff;
$base0d: #82aaff;
$base0e: #c792ea;
$base0f: #ff5370;
```
The following skins' code block colors have been …
> Improve syntax highlighting styles

- _includes/seo.html
When the name includes &quot; then the resulting schema is invalid. This is a fix.
> Fix jsonify name in seo.html application/ld+json script

- docs/_docs/04-upgrading.md
It's a trivial typo that I found when reading your documents.
In "minimal-mistakes/docs/_docs/04-upgrading.md", it seems a verb is missing in "To check which version you are currently using, view the source of your built site and you should something similar to:
".
Thank you for the amazing Jekll theme. 👍
> fix a typo in 04-upgrading.md

- CHANGELOG.md
- _config.yml
- _includes/scripts.html
- _includes/search/algolia-search-scripts.html
- _includes/search/lunr-search-scripts.html
- _includes/search/search_form.html
- _includes/search_form.html
- _layouts/default.html
- _layouts/search.html
- _sass/minimal-mistakes/_search.scss
- docs/_config.yml
- docs/_docs/05-configuration.md
- docs/_docs/18-history.md
- test/Gemfile
- test/_config.yml
- test/_pages/search.md
> Add Algolia search provider

- _data/ui-text.yml
Hi Michael,
I've fixed a small typo in ui-text.yml regarding language code for Polish language. Fix is trivial, so nothing special to explain, just da-PL changed to pl-PL
Thank you and Best Regards
Artur
> polish language code fix

- _config.yml
- _includes/analytics-providers/google-gtag.html
- _includes/analytics.html
- docs/_docs/05-configuration.md
For documentation see https://developers.google.com/analytics/devguides/collection/gtagjs/
and https://support.google.com/analytics/answer/7538414.
> Add support for Google Analytics with global site tag (gtag.js)

- _sass/minimal-mistakes/_utilities.scss
- _sass/minimal-mistakes/_variables.scss
Resolves #1653
* Of the four official brand colors documented on [brandcolors.net](https://brandcolors.net/b/gitlab) (fca326, fc6d26, e24329, & 554488), selected e24329.
* Also, there is currently only one [GitLab FontAwesome icon](https://fontawesome.com/icons?d=gallery&q=gitlab&s=brands&m=free).
> Add GitLab social icon brand color

- _sass/minimal-mistakes/_footer.scss
> Prevent line breaking between icon & text in footer social links

- docs/_docs/13-collections.md
- docs/_pages/pets.md
- docs/_pages/recipes-archive.md
Nice theme.  I was experimenting with it and noticed that the link to recipes was broken, and that the link to pets wasn't complete.
> fix broken recipe collection and make pets work

- _layouts/tags.html
It was being done twice, and it doesn't seem to need to be.
> DRY `tags_max` calculation in _layouts/tags.html

- _includes/seo.html
The current code prevented any separator being included when site.title_separator was unset.
> Include a default title_separator

- _data/ui-text.yml
Here are some updates on french labels.
A lot of time since I used the theme. It's usage as a ruby gem is a lot easier for updates ! Thank you for that ! 😃
> Update french labels

- docs/_docs/05-configuration.md
If the 'path' begin with a slash, you will receive the following error message when you post a comment
```
{
"success":false,
"rawError":
{
"code":422,
"status":"Unprocessable Entity",
"message":"{\"message\":\"path cannot start with a slash\",\"errors\":[{\"resource\":\"Commit\",\"field\":\"path\",\"code\":\"invalid\"}],\"documentation_url\":\"https://developer.github.com/v3/repos/contents/#update-a-file\"}"
},
"errorCode":"GITHUB_WRITING_FILE"
}
```
> remove the slash at the beginning of the 'path' in staticman.yml's example

- _sass/minimal-mistakes/_sidebar.scss
Had the same issue as in https://github.com/mmistakes/minimal-mistakes/issues/1554
So, should there be additional demand for having emojis in sidebar, this style change fixes it.
> Fixing scaling issue w. emoji in Sidebar Author Profile

- _data/ui-text.yml
- docs/_docs/08-ui-text.md
Added translations for Romanian
> Update ui-text.yml with Romanian translation

- _config.yml
- _includes/comments.html
- docs/_config.yml
- docs/_docs/05-configuration.md
- test/_config.yml
> Allow custom Staticman endpoints

- CHANGELOG.md
- _sass/minimal-mistakes/_archive.scss
- docs/_docs/18-history.md
Increase the click/tap targets of archive and feature items by making the entire parent clickable. This expands it from just the title or action button to excerpt and image.
> Make entire archive/feature item "clickable"

- CHANGELOG.md
- _config.yml
- _includes/scripts.html
- _layouts/default.html
- docs/_config.yml
- docs/_docs/18-history.md
- minimal-mistakes-jekyll.gemspec
- test/_config.yml
Includes that are computational expensive and are called several times can potentially see a improvement in build time if cached. Includes that do not rely on the `page` context are prime candidates for caching e.g. the masthead, footer, scripts, etc.
Install [jekyll-include-cache](https://github.com/benbalter/jekyll-include-cache) and replace includes that fit this criteria using `{{ include_cached }}` tag.
[**`/test` build times (Windows 7):**](https://github.com/mmistakes/minimal-mistakes/tree/master/test)
|  | `{{ include }}` | `{{ include_cached }}` |
| --- | --- | --- |
| cold start | 11.442s | 10.633s |
| rebuild | 10.136s | 9.136s |
> Cache "static" includes to improve build performance

- CHANGELOG.md
- _includes/scripts.html
- _layouts/default.html
Reverts caching for comments and analytics providers.
Fixes #1905. Although the issue only covered comments, I've uncached the `analytics.html` file as well since:
- the include that brings it in (`{% include scripts.html %}`) is now uncached
- it [uses a `page` variable](https://github.com/mmistakes/minimal-mistakes/blob/c8f4820d31c6b4c605ec96f74213df007c74c7cd/_includes/analytics.html#L1) that [can't be cached to work properly](https://github.com/mmistakes/minimal-mistakes/issues/1905#issuecomment-432040761)
> Revert caching for comments and analytics

- docs/_docs/05-configuration.md
This change remove unnecessary closing bracket in this section:
https://mmistakes.github.io/minimal-mistakes/docs/configuration/#analytics
in table, row with "Google Analytics Global Site Tag)"
No, it's not related to any GitHub issue. This is just a quick fix in the documentation.
> Remove unnecessary closing bracket

- _includes/scripts.html
Proposed fix for #1920. 
As the script is loaded from an external CDN (use.fontawesome.com), its integrity must be ensured mainly for security reasons.
This hash must be updated together with the exact version of Font Awesome, as given on their website.
I have **not** added the `crossorigin="anonymous"` policy as proposed by Font Awesome as it is a quite different topic, with implications I don't fully understand.
> add integrity hash for Font Awesome script

- _includes/author-profile-custom-links.html
- _includes/author-profile.html
- _includes/footer.html
Add rel attribute to social media links. 
Set value noopener for security reason. Otherwise you can get to opener information using `window.opener.document`. 
Set value nofollow to inform search engines that we don't want to count a link as a vote for that url. Social media have no problem getting users. They don't need dofollow links.
Set value norefferer to hide referrer information when the link is clicked. This is an option for more privacy in social media. They know so much.
It's not related to any GitHub issue.
> Add rel attribute to social media links in author profile and fotter

- _includes/video
- docs/_docs/14-helpers.md
As discussed in #1867.
Vimeo embed reference: https://help.vimeo.com/hc/en-us/articles/360001494447-Using-Player-Parameters
For YouTube, this embed URL is found in the 'Embed' window for any video, by scrolling down in the right pane ('Enable privacy-enhanced mode').
> Use privacy aware embed options for YouTube & Vimeo

- README.md
- _data/ui-text.yml
- docs/_pages/about.md
There are more than 100 million native speakers of Punjabi language. I am one of them. More details about [punjabi on wikipedia](https://en.wikipedia.org/wiki/Punjabi_language).
All the punjabi translations are perfect with the following exceptions-
- in the variable name (_config.yml and words_per_minute) which are intentionally left in english.
- meta_label is empty
**This is an enhancement or feature.** 
Add translation for ui-text in Punjabi.
It's not related to any GitHub issue.
> Punjabi Translation of ui-text

- CHANGELOG.md
- _config.yml
- _includes/comments-providers/scripts.html
- _includes/comments-providers/utterances.html
- _includes/comments.html
- docs/_config.yml
- docs/_docs/02-structure.md
- docs/_docs/05-configuration.md
- docs/_docs/18-history.md
- docs/_pages/about.md
- test/_config.yml
Adds support for [utterances](https://utteranc.es/), a lightweight comments widget built on GitHub issues.
#1909
> Add support for utterances

- _includes/breadcrumbs.html
Using secure links (https) for schema.org
It's not related to any GitHub issue.
> Changed schema.org to secure links (https)

- _layouts/single.html
posts) section
When I forked this repo and created my first post, I noticed that in the "You may also enjoy" section, this first post was include, which doesn't make much sense. I have added a check to skip the current post when populating the related_posts.
> Prevent current post from showing in the "You may also enjoy" (related

- _includes/archive-single.html
- _includes/author-profile.html
- _includes/comment.html
- _includes/search/algolia-search-scripts.html
- _includes/seo.html
- _layouts/single.html
- _layouts/splash.html
- assets/js/lunr/lunr-en.js
- assets/js/lunr/lunr-gr.js
did a find/replace of all "http://schema.org" to make it https.
Related to https://github.com/mmistakes/minimal-mistakes/pull/1969#issuecomment-441875298 
``` bash
jbr@Rummels-MBPr ~/D/GIT> find minimal-mistakes -type f -exec grep "http://schema.org" "{}" \; -print | grep minimal
minimal-mistakes/_includes/author-profile.html
minimal-mistakes/_includes/seo.html
minimal-mistakes/_includes/search/algolia-search-scripts.html
minimal-mistakes/_includes/archive-single.html
minimal-mistakes/_includes/comment.html
minimal-mistakes/_layouts/single.html
minimal-mistakes/_layouts/splash.html
minimal-mistakes/assets/js/lunr/lunr-gr.js
minimal-mistakes/assets/js/lunr/lunr-en.js
jbr@Rummels-MBPr ~/D/GIT> sed -i '' 's|http://schema.org|https://schema.org|g' …
```
> secure schema.org

- _includes/search/search_form.html
- _layouts/search.html
fbafe58e40b1bd4a2628aef1eb5955ab57dcfaf4 renamed the function in the
scripts file, but did not rename the call sites.
Google Custom Search integration does not work if Instant Search is not enabled.
In my `_config.yml`, I had:
```
google:
search_engine_id       : "my_id"
instant_search         : # false (default), true
```
When I tried to execute a search, I got an error in the Javascript console about `executeQuery` not being defined.
As part of #1667, a function was renamed in fbafe58e40b1bd4a2628aef1eb5955ab57dcfaf4. However, the two call sites, in `_includes/search/search_form.html` and `_layouts/search.html`, were not renamed.
> Google Custom Search does not work if not using Instant Search

- _data/ui-text.yml
The Spanish translation of `comment_title` is *misplaced*, while that of `comment_label` is *missing*.
Taken from line 91 in `messages.php` in kekebeen/5d-eu@ec56008
> [Bug fix]: Added missing Staticman Spanish UI text

- _includes/head.html
works exactly the same since IE 10 doesn't support IE conditional statements.
saves 5 bytes :-)
> shorter IE conditional statement

- _data/ui-text.yml
- _includes/masthead.html
I recently switched my site to use the latest minimal mistakes theme. I ran an audit and noticed that it scored 68 for accessibility.
I looked into it and of the issues is that the search toggle button does not have a discernable name: 
> ![screenshot of the chrome audit](https://user-images.githubusercontent.com/2148318/50569306-0c738780-0d30-11e9-8197-9b23894bf9b3.png)
When [looking into it](https://dequeuniversity.com/rules/axe/2.2/button-name?application=lighthouse) I saw it could be fixed by adding an `aria-label`, so I figured I'd contribute that back.
This PR adds an `aria-label` to the search toggle button. I'm open to any preferences on the specific wording to use.
> Accessibility: Add aria-label to the search button

- _includes/comments-providers/utterances.html
Current we hardcoded the `pathname` for `issue-term` when we are using utterances comment provider.
It would be better for let users customize it by setting a `site.comments.utterances.issue_term` in their `_config.yml`.
> Add support to customize `issue-term` for utterances comment provider

- _data/ui-text.yml
> Add Malayalam localized UI text strings

- _includes/author-profile.html
**Stack Overflow** is no longer including `www` in its URLs.
> Remove 'www' from Stack Overflow URL

- assets/js/_main.js
Dear the make of one of the world's greatest jekyll theme.
[problem]
I found that
'Syntax Error' occurs when non-english character is included in some html elements(e.g h2, h3 ...) and 'toc' is generated based of that elements.
[debug]
Click the any element of auto generated 'toc' in the below link.
https://aliwo.github.io/swblog/series/principles_of_python/object/#%EA%B0%9D%EC%B2%B4%EC%99%80-%ED%81%B4%EB%9E%98%EC%8A%A4%EC%9D%98-%EC%A0%95%EC%9D%98
[fix]
This happens because escaped url string get right in to jquery. So I fixed it with
javascript's 'decodeURI' function! :)
> [fix] syntax error of non-english character

- _data/ui-text.yml
Updated the Swedish translations:
Added missing translations for `search_label`,  `search_placeholder_text`, `results_found` and `back_to_top`.
Fixed some of the translations to more correct Swedish.
No issue exist for this PR.
It's a minor pullrequest to just correct and update some of the translations in the Swedish translation map.
> Updated swedish translations

- _includes/figure
`</figure>` tag in in the `figure` include should be in the same line as `</figcaption>` because if it isn't jekyll adds an extra end-tag `</figure>` when the figure is inside of a list. As you can see bellow. 
With this... it doesn't happen and the list numbers continue as normal. 
The include has to be indented 4 spaces to be include in the list. 
I guess this is more a jekyll bug than anything else, but doing this is fixed.
> Fix figures when they are inside of a list

- _sass/minimal-mistakes/_masthead.scss
- _sass/minimal-mistakes/_page.scss
- _sass/minimal-mistakes/_search.scss
- _sass/minimal-mistakes/_variables.scss
I really don't know if you are interested in adding this to the theme. It comes to resolve a problem that is mainly there when you change the size of the browser in computers, o you have a small screen computer or an iPad. It felt that sometimes in smaller browser sizes some content was bigger, wider, than in bigger ones for no reason. 
Create a new breakpoint in between "large" and "x-large" so the size changes are a little bit more fluid.
Tune-up how the right and left sidebars and the post/page content behaves. It feels more fluid now and usually when the size of the browser decreases the content decreases. Before at some breakpoints the content was bigger than in the wider breakpoint.
Create a $max-width variable, so know the content can be wider …
> Add variable for max-width

- _includes/scripts.html
- docs/_docs/17-javascript.md
Make it easier for theme users to add JavaScript after the theme's scripts. Use a similar method to `footer_scripts` arrays in `_config.yml` to reference paths to external or locally hosted JavaScript files.
#2110
> Allow adding JavaScript files after those bundled in the theme

- _includes/search/search_form.html
Updates Issue #2122 by adding the correct input type and aria placeholder.
Changes the browser UX upon search type & adds ARIA placeholder.
More information can be found at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search
> Improve search `input` semantics

- _sass/minimal-mistakes/_forms.scss
Sass do not correctly compile division without parenthesis.
> Arithmetic fix in _form.scss

- docs/_docs/05-configuration.md
- docs/_posts/2013-01-10-markup-image-alignment.md
- minor edits to 05-configuration.md
- minor edits to 2013-01-10-markup-image-alignment.md
also fyi:
- Flickr link used in [2012-03-15-layout-header-image-external.md](https://github.com/mmistakes/minimal-mistakes/blob/57a4324fa04086ee8c035a6969d3c415f250e556/docs/_posts/2012-03-15-layout-header-image-external.md) is dead
- Flickr link used in [2010-08-05-post-image-linked.md](https://github.com/mmistakes/minimal-mistakes/blob/57a4324fa04086ee8c035a6969d3c415f250e556/docs/_posts/2010-08-05-post-image-linked.md) is dead
n/a.
> Low hanging fruit

- _includes/analytics-providers/google.html
remove unneeded  type="text/javascript" from google analytics
REF: 
- https://google.github.io/styleguide/htmlcssguide.html#type_Attributes
- https://codeguide.co/#html-style-script
- https://developers.google.com/analytics/devguides/collection/analyticsjs/
> remove unneeded  type="text/javascript" from google analytics

- _data/ui-text.yml
Hi!
Thank you for sharing your awesome themes.
I found that some lines are missing in "ko" locale in /_data/ui-text.yml:
- search_placeholder_text
- results_found
- back_to_top
I'v added translations for them based on most commonly-used words in Korea.
Nothing related to any other issues.
> Complete missing parts of Korean locale.

- _includes/masthead.html
- _sass/minimal-mistakes/_masthead.scss
- _sass/minimal-mistakes/_variables.scss
Displays `site.subtitle` in masthead under the site title.
Related to issue #2173
> Display site subtitle in masthead

- _data/ui-text.yml
- _includes/search/search_form.html
- _sass/minimal-mistakes/_search.scss
Allows search input to have aria-label defined through language conflict, which resolves the A11y issue of an input without a label.
Also removes aria-placeholder from the search label, as per [ARIA](https://www.w3.org/TR/html-aria/) 
```
Use the placeholder attribute on any element that is allowed the placeholder attribute in HTML5
Only use the aria-placeholder attribute on elements that are not allowed to have a placeholder attribute in HTML5.
```
Resolves issue: [2180](https://github.com/mmistakes/minimal-mistakes/issues/2180)
> Fixes aria issues on search form

- _config.yml
- _includes/author-profile.html
- test/_config.yml
I enabled markdown in the author bio. Previously, markdown was not enabled. In other words, I added the `markdownify` Liquid Filter to `{{ author.bio }}`.
I tested this edit locally and it worked perfectly.
I wanted to be able to write stylized text and insert links into the bio section of the author info sidebar.
> Allow Markdown in author bio

- _config.yml
Every site should support https by now. Better to link the https sites right away. Both sites do support https at the time I checked.
I changed the protocol of some links given in the comments of the config file from http to https since all sites should make use of https in 2019
This PR is not related to any GitHub issues.
> Fix http links to use https

- _includes/read-time.html
Different languages usually have different read speeds so it makes sense for sites with multi-lingual content (like [my site](https://ibugone.com/) where I write both English and Chinese) to be able to specify `words_per_minute` on a per-page basis.
I have already fired up another PR (jekyll/jekyll#7813) to handle the counting of CJK characters "words" and in combination with this PR, Minimal Mistakes will be better in i18n.
> Allow per-page override of words_per_minute

- _includes/head.html
> remove extraneous space from IE conditional statement

- README.md
Added Smooth Scroll and Gumshoe info
> Update the info about what js scrips you are using

- _sass/minimal-mistakes/_utilities.scss
- test/_posts/2009-05-15-edge-case-nested-and-mixed-lists.md
Fixes #2283 
Allowing nested GFM task list to be indented correctly.
Related to #2283
> Fix and test case

- docs/_docs/13-collections.md
The step is required to get the portfolio collection to work.
Explicitly describes a short vital step that is required to get collections to work. 
Related to an issue where somebody couldn't get the collections to work.
> Added another step to the collections docs

- .gitignore
- _config.yml
- _layouts/archive-taxonomy.html
`archive` layout already supports page hero, so why not `archive-taxonomy`? Since `jekyll-archives` generates pages based on this layout, it'd be nice to have it support more beautiful layouts as well.
> Support page header (page hero) in archive-taxonomy layouts

- _sass/minimal-mistakes/_utilities.scss
- _sass/minimal-mistakes/_variables.scss
This PR adds the color to the [Keybase](https://keybase.io) social icon.
This isn't related to any issues on Github.
> Add social icon color for Keybase

- _sass/minimal-mistakes/_notices.scss
Before this patch, code blocks `<pre><code>` in notices are hardly readable:
> ![before](https://user-images.githubusercontent.com/7273074/69306294-f03b4a80-0c61-11ea-95ea-01dd244feedf.png)
After this patch, they look certainly better!
> ![after](https://user-images.githubusercontent.com/7273074/69306301-f4fffe80-0c61-11ea-8cef-d66e26d757b8.png)
> Fix unreadable code blocks in notices

- _includes/comment.html
- _layouts/single.html
- _layouts/splash.html
It seems that [schema.org's *date* data type](https://schema.org/Date) should be ISO-8601. So I updated `datePublished` and `dateModified` format to [`date_to_xmlschema`](https://jekyllrb.com/docs/liquid/filters/).
> Fix schema.org dates to ISO-8601

- _includes/comments.html
According to the most recent docs, `branch` and `endpoint` should be inside `site.comments.staticman` config instead of `site.staticman`.
https://mmistakes.github.io/minimal-mistakes/docs/configuration/#staticman-v3
> Fix staticman v2/v3 comments not showing

- _includes/comment.html
- _layouts/single.html
Use `%-d` instead of `%d` so displayed dates aren't padded with zero. For example, *January 03* becomes *January 3*, which looks surely better to humans.
Reference for this behavior of Ruby `DateTime#strftime`: <https://apidock.com/ruby/DateTime/strftime>
> Use %-d instead of %d for display dates

- _config.yml
`package.json` was being removed but `package-lock.json` wasnt.
This PR fixes that.
> 🔧 Exclude `package-lock.json`

- _includes/page__hero.html
Allow the use of `page.tagline` to override `page.excerpt` in heading area.
I want to have some custom text that more resembles a "description" of the article in the header area that's designated for the excerpt. However, manually overriding `page.excerpt` in front matter also changes the excerpt displayed in blog menu / pagination pages, which is a rather undesired impact. Using another variable like `page.tagline` to override this makes it easier to handle and more flexible to use.
For example, the text \[*Developer, system administrator, geek*\] on [my front page](https://ibugone.com/) is actually specified as `page.excerpt`:
https://github.com/iBug/iBug-source/blob/9837ea293a154b154404a18d533341dc93199cb5/index.md#L3
Not related to any existing …
> Allow override of page excerpt in heading (via tagline)

- LICENSE
- README.md
- docs/_docs/01-quick-start-guide.md
Updated README for a few small fixes:
- *You'll **throw** an error* is wrong in English, changed to *You'll **encounter** an error*
- The theme has 10 skins including the default one, so the text above is changed from ***including** the default one* to ***in addition to** the default one*
- Updated licensing information to reflect year change (2019 → 2020)
The second commit changed two RawGit links to jsDelivr since [RawGit has been deprecated since October 2018](https://rawgit.com/).
> Update README and LICENSE

- _includes/seo.html
This is a bug fix for #2354. See that thread for details.
> Fix wrong newline concatenation in SEO description

- _includes/comments-providers/disqus.html
Since enabling compress_html at my page the disqus comments haven't been shown. When looking at the compressed page code I've saw that the `//` comments are also disabling the code after that as compression removed the line-breaks.
Using `/* */` for comments clearly wraps the comment and doesn't deactivate any code afterwards.
- see also Restrictions at https://jch.penibelst.de/ 
- I added this changes to my repo, so you could see it running (and working at) https://gamue.de/
> Adjust comments to be compatible with compress_html

- _layouts/home.html
It allows using the theme without pagination.
Right now if you get this theme, it will not show any posts on the homepage unless you add an `index.html` file and enable pagination in `_config.yml`. This change reduces this friction and some head-scratching as to why no posts are showing on the homepage.
> Allow using theme without pagination

- _layouts/home.html
The patches in #2378 introduced a huge issue when paginating collections with paginate V2 plugin, the users of which generally set `site.paginate` to `false` or omit it completely to let it default to `null`. This however made all collection indices paged with `site.posts` instead of `paginator.posts`.
Tested with Jekyll 3.8.6 and latest compatible `jekyll-paginate-v2`, the `paginator` object is available for properly-configured pages, so this change doesn't break the intended functionality of #2378, while fixes the new issue effectively.
> Fix compatibility issue with paginate V2 introduced by #2378

- CHANGELOG.md
- _includes/masthead.html
- docs/_docs/18-history.md
On the merged commit of #2332 (abf29432f6e4d75a13e94a20d8a8fc93953ee9e7), there's already
<https://github.com/mmistakes/minimal-mistakes/blob/abf29432f6e4d75a13e94a20d8a8fc93953ee9e7/_includes/masthead.html#L12>
Emphasis:
```html
^^^^^^^^^^^^^^
````
so the extra `relative_url` is the culprit for the duplicated base path for masthead logo when `site.baseurl` isn't resolved to `/`.
This PR resolves that bug by removing the extra `relative_url`. On a side note, I wouldn't blame the original PR suggester because the initial `{% if site.logo contains "://" %}` is rather misleading per se.
#2332 Comment: <https://github.com/mmistakes/minimal-mistakes/pull/2332#issuecomment-579856138>
cc @Geekdude
> Regression for mmistakes#2332

- _sass/minimal-mistakes/_forms.scss
> box-shadow on radio buttons and checkboxes look ugly

- _includes/comments-providers/staticman_v2.html
This fixes the issue of the user being redirected away from the website to a JSON file after submitting a comment, rather than an alert box showing up on the page letting them know if their comment was successfully submitted or not as intended.
This bug was introduced by PR #2351 where it changed the `site.staticman.branch` variable path to `site.comments.staticman.branch` for staticman v2, but missed the naming refactor in staticman_v2.html.
> fix: Do not redirect user away from site after they submit a comment

- _includes/documents-collection.html
- _includes/posts-category.html
- _includes/posts-tag.html
Hide posts which have `hidden: true` in their front matters from collection / category / tag listings, as is already done with `home` layout. This works for listing pages with `layout: collection OR category OR tag`.
> Hide posts with [hidden: true] from listings

- _includes/archive-single.html
- _includes/author-profile.html
- _includes/feature_row
- _includes/figure
- _includes/gallery
- _includes/head.html
- _includes/masthead.html
- _includes/nav_list
- _includes/page__hero.html
- _includes/scripts.html
- _includes/seo.html
- _includes/sidebar.html
- assets/js/lunr/lunr-store.js
Since Jekyll 3.7.0 the `relative_url` filter does nothing when given an absolute URL, which eliminates the need to manually check for `url contains "://"`. This saves a lot of effort when coding.
A similar behavior for the `absolute_url` filter had already been introduced earlier in jekyll/jekyll#5789 and was released with Jekyll 3.5.
I ran both `grep -nrF 'contains "://"'` and `grep -nrF "contains '://'"` (single- vs. double-quotes) and reviewed every single occurrence of them, and refactored wherever possible / makes sense.
Jekyll 3.6 would no longer be compatible with this theme after merging this PR.
https://github.com/mmistakes/minimal-mistakes/pull/2385#issuecomment-579882236
> Use relative_url and absolute_url where possible

- docs/_docs/06-overriding-theme-defaults.md
Fix minor deprecation issue with bundler show vs now info. 
Just to avoid unnecessary warning for users.
> Fix minor deprecation issue

- _includes/paginator.html
Use `paginator.first_page_path` from Paginate V2 plugin for better compatibility. The original `jekyll-paginator` doesn't have this variable so this PR will not affect sites using original paginator.
I was reviewing my local overrides of the theme when I noticed this change and I even forgot what the problem was (what this change solved) but I hope this is helpful.
> Use first_page_path from Paginate V2 if available

- docs/_docs/05-configuration.md
Update documents to clarify Lunr only searches documents in collections or posts.
I'm newbie of jekyll and github pages, and I couldn't figure out why my pages under `/docs` directories cannot be searched for a couple of hours.
So, I think it's gonna be great if we explicit say `documents in collections` can be searched, so that newbies can understand.
It looks this PR is related with https://github.com/mmistakes/minimal-mistakes/issues/1663#issuecomment-387790192
> Clarify lunr only searches documents in collections

- _data/ui-text.yml
I've just updated some of the missing labels for Vietnamese.
This is not related to any GitHub issue(s).
> Add missing Vietnamese translations

- _includes/author-profile.html
- _sass/minimal-mistakes/_sidebar.scss
**This is a bug (style) fix.**
Author profile page uses a literal ` ` space character as padding between the social icon and the text. Which as a result causes the underline to show up on a blank space character on hover, causing it to look like the example below.
This PR wraps the text with a `span` block that can be used to customize spacing between the social icon and its relevant text, making it a breeze to customize as opposed to copying `author-profile.html` to your local repo and customizing it just to fix spacing, making upgrading the theme very difficult.
> Use css padding for author urls to fix underline hover state

- CHANGELOG.md
- _sass/minimal-mistakes/_archive.scss
- _sass/minimal-mistakes/_sidebar.scss
- docs/_docs/18-history.md
> Fix #2478 "Follow menu falls under post links"

- CHANGELOG.md
- docs/_docs/18-history.md
- docs/_pages/home.md
- docs/_pages/page-archive.html
This is a bug fix.  
#2481 is a really interesting finding, and I would doubt anyone wants the index page listed in the archive (at least not for this theme).
This fix basically reuses the idea from #2345.
> Hide index page from page-archive, resolves #2481

- CHANGELOG.md
- _sass/minimal-mistakes/_sidebar.scss
- docs/_docs/18-history.md
Currently, with sticky (left) sidebar enabled, the footer is pushed down beyond the first screen plus the height of the header area, which may be visually unintuitive. This PR changes the forced `height` into `max-height` for a better look in this case.
- **Before**: [image](https://user-images.githubusercontent.com/7273074/80823984-2668f700-8c10-11ea-9f74-eefb81b5e6f4.png) (Look! Scrollbar!)
- **After**: [image](https://user-images.githubusercontent.com/7273074/80823854-eb66c380-8c0f-11ea-80b9-7ea677ac37a6.png) (Note: No scrollbar on the right)
Tested with Chrome 81 (Windows 10 & macOS Catalina), Firefox 74, and Edge 44. [Here](https://ibugone.com/status/)'s a live page on my website with this patch included.
> Make sticky sidebar live well with short content

- docs/_docs/01-quick-start-guide.md
This theme now requires Jekyll 3.7, but the Quick-Start Guide page still reads "3.5" and thus should be fixed.
Side changes are some `http:` to `https:`. The two affected domains (`bundler.io` and `jekyllrb.com`) have long been HTTPS only.
> Bump Jekyll version note from 3.5 to 3.7

- _includes/seo.html
Related to #2541 . This will strip the extra whitespace in the end of seo_description.
> Strip trailing whitespace in seo_description

- CHANGELOG.md
- _includes/head.html
- _includes/scripts.html
- docs/_docs/18-history.md
Instead of using Font Awesome Kits, load its CSS from [jsDelivr CDN][1].
✔ Font Awesome official source and NPM package
✔ Always up-to-date with latest FA 5 icon sets
✔ Faster everywhere (jsDelivr is the largest public NPM CDN, also works in China)
✔ Loads fewer bytes
✔ No bothering with `async` and/or `defer`. Always loaded asynchronously and displayed as soon as it's ready
✔ Works with ads blocker
✔ Works even with JavaScript disabled
Potentially related: #413
[1]: https://www.jsdelivr.com/package/npm/@fortawesome/fontawesome-free
> Load Font Awesome CSS from jsDelivr CDN

- _includes/archive-single.html
If you use archive-single.html on e.g. a single page, then the TOC will break. One solution is to no include the H2 deliverede by archive-single.html in the TOC.
When using this to include posts in another post:
```
{% assign site_posts = site.routes | where: "tags", "børnevenlig" | sort: "title" %}
{% if site_posts.size > 0 %}
{% for post in site_posts %}
{% include archive-single.html %}
{% endfor %}
{% endif %}
```
I end up with this TOC:
> Ignore teaser headline in table of contents

- README.md
This is a bug fix
The current wtpl license in the README is dead, so I'm updating it to use the current. The site doesn't have https, so if you want https we could also use https://choosealicense.com/licenses/wtfpl/.
> Updating link to wtfpl license

- _data/ui-text.yml
- _includes/search/algolia-search-scripts.html
Search using algolia on menu toggle
With that change search is performed when requested. Before it was done
for each pageview, regardless of the fact if search was used by user or
not.
No.
> Algolia search update

- CHANGELOG.md
- _includes/page__hero_video.html
- _includes/video
- docs/_docs/14-helpers.md
- docs/_docs/18-history.md
The original author of #2522 hasn't returned to GitHub in more than 2 months, so I'll take the courtesy of completing that PR.
Basically what's been proposed in the original PR, plus my own review suggestions applied.
Rewritten `_include/video` to use a `case-when` clause for the iframe `src` attribute, so other HTML attributes need not repeat for each video provider.
#2522
> Enhance Bilibili video support (redo of #2522)

- _sass/minimal-mistakes/_notices.scss
In notice blocks, H4 elements appear too close to the following paragraph. This PR remediates that by adding `line-height: inherit` to those H4s.
It's probably too minor a change, but if you examine closely, the vertical space between the H4 and the next paragraph is even shorter than that between the two lines of the paragraph.
Before:
After:
None
> Give H4 in notice some space from below

- _config.yml
- docs/_config.yml
- test/_config.yml
The comment provided in `_config.yml` for `analytics.provider` is not complete (missing google-gtag).
The main config's `analytics.provider` comment was properly amended by the google-gtag feature commit (79d0b75683a4c13787b117e9e612073586fa21be), but the comment was reverted, possibly by bad merge, with an unrelated commit (bac26e96b21f846df6ede382e8c7ee4019564eab) two days later.
The docs and test configs appear to have never received the initial google-gtag update.
This change fixes all three configs' `analytics.provider` comments.
Comments are good.
> Fix "analytics.provider" config comment to list all analytics providers.

- _sass/minimal-mistakes/_notices.scss
I'm sorry for having to submit this "redundant" PR. I didn't notice I had set `autocmd FileType scss set noexpandtab` in my editor config, so that PR (#2602) had some inconsistencies w.r.t. indentation styling.
This PR changes the "faulty" tab indentation into spaces. I also moved `line-height` to below `margin-bottom` so it looks better, as similar items are grouped together.
Probably too minor to worth a separate line in the changelog, though, as this *should have been* done in 2602, instead of in this separate PR.
2602: <https://github.com/mmistakes/minimal-mistakes/pull/2602/files>
> Change tab indent to space for consistency

- CHANGELOG.md
- assets/js/lunr/lunr-en.js
- assets/js/lunr/lunr-gr.js
- assets/js/lunr/lunr-store.js
- docs/_docs/18-history.md
Use `layout: none` instead of `layout: null` for Lunr JS files.
The `none` special layout is supported since Jekyll 3.7 (we're already requiring that as the minimum version) as a more robust replacement for either a missing key or `layout: null`. This should fix compatibility issues with Jekyll 4.1.0 (and potentially future issues should Jekyll decide to update something else).
See <https://github.com/jekyll/jekyll/issues/8217#issuecomment-640014789> (comment from Jekyll maintainer).
While it's in fact an upstream issue, a fix on our side should be harmless and good to have.
Fixes #2615
> Use layout: none instead of null

- _layouts/home.html
- _sass/minimal-mistakes/_archive.scss
This allows to use grid layout on `page.entries_layout` on the home layout.
There is support for layout grid on most places but home page.
I mimicked how it's done on posts/categories/tags to allow that on home page. See demo at www.cornerinthemiddle.com
Included a break since when using grid the post images are too close to the horizontal line bellow `posts` text.
There's a entries div now surrounding the posts since the first row of the grid was having a slight padding on the left. The home now behaves like posts/categories/tags pages with grid but including the paginator.
Tested on mobile renders ok and on hd desktop, for best results on desktop we can use `classes: wide` and `paginate: 4` on `_config.yml` (or multiples of 4 if you want more rows)
> Configure entries layout `list` or `grid`

- CHANGELOG.md
- docs/_docs/01-quick-start-guide.md
- docs/_docs/06-overriding-theme-defaults.md
- docs/_docs/18-history.md
As discussed in the linked issue.
Resolves #2621
> Update documentation for #2621

- _sass/minimal-mistakes/_footer.scss
- _sass/minimal-mistakes/_sidebar.scss
This is a bug fix / improvement
- `.author__urls-wrapper` has a duplicated `position: relative;` definition
- `. page__footer ` includes `clearfix` and defines ´clear: both;` on it's own which is duplciated then
> Removed duplicated CSS definitions

- CHANGELOG.md
- docs/_docs/01-quick-start-guide.md
- docs/_docs/18-history.md
> Fix dead link to "CI services" Jekyll

- _includes/figure
This patch removes redundant `</figure>` tag rendered as text when the figure helper is used in a list, either ordered or unordered, and no caption is specified for that figure.
```md
---
layout: single
---
1. Lorem ipsum dolor sit amet
{% include figure image_path="https://raw.githubusercontent.com/mmistakes/minimal-mistakes/master/screenshot.png" alt="Test image" %}
2. The quick brown fox jumps over the lazy dog
```
The above post is going to be rendered as in the image below. The figure is not captioned, which produces a redundant `</figure>` below it. Another noticeable issue is the next item that is supposed to be in the same list is put in a new list, resetting the number to 1.
After this patch is applied, the same post can be rendered correctly.
The figure …
> Fix Closing Tag of Figures Without Captions in Ordered and Unordered Lists

- CHANGELOG.md
- docs/_docs/14-helpers.md
- docs/_docs/18-history.md
`embeded` → `embedded`
The original spelling missed the double D.
> Fix a small typo in documentation

- README.md
- docs/_docs/01-quick-start-guide.md
Update remote theme installation instructions to indicate that `jekyll-include-cache` should be added to the Gemfile.
I followed the [remote theme installation](https://github.com/mmistakes/minimal-mistakes#remote-theme-method) instructions and got the following error when running `bundle exec jekyll serve`:
```
Dependency Error: Yikes! It looks like you don't have jekyll-include-cache or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-include-cache' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
```
Adding the `jekyll-include-cache` gem to my Gemfile resolved the error, so it …
> Update remote theme instructions

- CHANGELOG.md
- _includes/toc.html
- _layouts/single.html
- docs/_docs/14-helpers.md
- docs/_docs/18-history.md
Headings without an `id` attribute cannot be located in the ToC. Previously the ToC generated entries with `href="#top"` (usually a non-existent ID) but since the update to v1.0.14 (#2700), it started generating bad entries that aren't properly styled.
The update of the template to v1.1.0 doesn't introduce new features to this theme, but the addition of `skip_no_ids` does. See the referred discussion below for details.
See #2751.
[1]: https://github.com/mmistakes/minimal-mistakes/commit/99a77e4d3a99c0d39735b2ff3550a1b5554d6e28#diff-ae5bddf889465c887d2c57e786a6b29f4ac82b277fcce0672ce8bbdba11ebf3aR49
> Update allejo/jekyll-toc to v1.1.0, skip headings without an ID

- docs/_docs/10-layouts.md
Only add the "toc_sticky" parameter to the Layouts page. It can be found on [Helper](https://mmistakes.github.io/minimal-mistakes/docs/helpers/#enabled-via-yaml-front-matter) page but can't be found on [Layouts](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#table-of-contents) page.
Related to #2665
> Add toc_sticky parameter's description

- assets/js/_main.js
Adds .webp to list of supported image extensions for the image popup lightbox.
I prefer to use .webp image assets, so this would be nice.
> Add .webp to supported lightbox images

- test/_pages/404.md
Unfortunately, fixurl.js no longer exists and I couldn't find a suitable replacement quickly. Submitting this to remove the bad link.
Per: 
* #2597 
* https://webmasters.googleblog.com/2008/08/make-your-404-pages-more-useful.html
* https://developers.google.com/search/blog/2008/08/make-your-404-pages-more-useful
> Remove google's fixurl.js from example

- _config.yml
- _includes/footer.html
- _includes/head.html
- docs/_docs/05-configuration.md
Adds a `hide` property to the `atom_feed` in `_config.yml`. When `hide` is set to `true` (`false` by default), prevents the header and footer from rendering the RSS feed icons.
Resolves #2786.
> Add toggle option for RSS feed visibility

- _includes/category-list.html
- _includes/tag-list.html
- The sorting logic for tags and categories is done by custom-logic. I thought it's cleaner code to use `sort_natural` which exists out of the box for that use-case. See documentation at https://shopify.github.io/liquid/filters/sort_natural/
- Afaik this method was introduced in Jekyll 3.5, means it would be a requirement to have at least that version. However it's been released some years ago and is supported by GitHub Pages, so don't think it's breaking something
> Use sort_natural instead of custom-logic

- _includes/documents-collection.html
- docs/_docs/10-layouts.md
This PR allows sorting of collections by custom keys. This is done by using directly the `include.sort_by` value in sort tag instead of testing it's value.
> Allow custom sorting for collections

- CHANGELOG.md
- _sass/minimal-mistakes/_forms.scss
- docs/_docs/18-history.md
> Remove Google-stuff CSS

- CHANGELOG.md
- _includes/masthead.html
- docs/_docs/18-history.md
> Add `alt` attribute to site logo in masthead

- .gitattributes
- docs/_docs/10-layouts.md
- docs/_docs/14-helpers.md
> Add note on TOC heading level issue

- _includes/seo.html
- docs/_docs/05-configuration.md
<-- This is an enhancement or feature. -->
Baidu is the top one search engine in China. There are many users in China using this theme and hope for Baidu SEO.
In this pull request, I simply add a Baidu `<meta />` in seo.html. 
No
> add baidu site verfication

- _includes/comments.html
- docs/_docs/05-configuration.md
- staticman.yml
1. removed any references to the public official API instance "api dot staticman dot net" as Staticman's maintains has recommended users to stay away from it.
1. replaced `api.staticman.net` in the docs with `{your Staticman API URL}` in the docs
2. (breaking change) removed the fallback to the public official API instance in the Jekyll-HTML template to encourage existing users to self-host their own instance
2. change `v2` to `v[2|3]` in the docs to encourage users to use the v3 API scheme.  For v3 users, the `/v2/encrypt` in `staticman.yml` might be confusing.
3. labelled the existing GitHub bot authorization mechanism as "legacy" in favor of the new GitHub App way, which avoids GitHub's rate API limit.
4. moved the link to Staticman's …
> Remove all references to official public Staticman API instance.

- _sass/minimal-mistakes/_notices.scss
- _sass/minimal-mistakes/_variables.scss
- _sass/minimal-mistakes/skins/_aqua.scss
- _sass/minimal-mistakes/skins/_dark.scss
- _sass/minimal-mistakes/skins/_neon.scss
- _sass/minimal-mistakes/skins/_plum.scss
- _sass/minimal-mistakes/skins/_sunrise.scss
This PR replaces the fixed color values of `$dark-gray` and `#fff` used to determine notice foreground and background colors with `$text-color` and  `$background-color`, respectively.  The old values are the defaults for the theme, so the default skin is unaffected.
I almost always use dark themes for my sites, and notices are very glaring as is:
With this PR, it is much easier on the eyes, and the background color changes are more obvious.
<details><summary>Screenshots of all prepackaged skins</summary>
</details>
> Color notices based on skin colors instead of fixed values

- _includes/head.html
Loading font-awesome asynchronously allows to display the site faster. This change is advised by google pagespeed insights
> Loads font-awesome asynchronously

- _includes/skip-links.html
This should not use a H2, as that is not an important headline, and thus a H2 here would probably hurt in page SEO.
> Remove H2 as it is not important to site structure

- _includes/head.html
Save some bytes in the HTML for all users by removing the fallback inline CSS.
IE9 is absolutely, completely, totally dead. it's marketshare is less than 0.1%.
REF: https://caniuse.com/usage-table
> Remove IE9 flexbox fallback

- _includes/breadcrumbs.html
Remove `site.url` from the top-level breadcrumb, so that the URL becomes relative just like the other (child) breadcrumb links.
This means that if a Jekyll site configured as `site.url: domain.com` the top/first/root breadcrumb will now point to `/` instead of `domain.com/`. This is important because the site might be deployed to `127.0.0.1` for local development or at `dev.domain.com` or such. Thus it should simply link to the root relative and not with `site.url`.
Fixes #3050
> Remove site.url from first breadcrumb link

- _data/ui-text.yml
Fixed a small grammar error in the german translation
> Fixed a grammar error in the german translation

- _layouts/single.html
- docs/_layouts/single.html
This PR is about changing the heading tag of related posts section from `h4` to `h2` for SEO enhancement. I have implemented the same on my website in [PR](https://github.com/kulbhushanchand/kulbhushanchand.github.io/commit/835332069f83fda3fff2eb75456d03ac5756c7cd) and working [demo](https://kulbhushanchand.github.io/website-is-up-and-ready/)
With reference to your comment on my post at https://github.com/mmistakes/minimal-mistakes/discussions/3040#discussioncomment-1010824
Since you have already provided the relevant font size, so any style change may not be required. https://github.com/mmistakes/minimal-mistakes/blob/3c075fe76b0971f3ccc63c6940b63306d6100fb2/_sass/minimal-mistakes/_page.scss#L529
> fix: change heading tag of related posts section from `h4` to `h2` for SEO enhancement

- docs/_docs/17-javascript.md
Add instructions on how to unminify the `main.min.js` for easier browser debugging.
I'm having issues looking very much the same like already reported in #2664 (that the greedy-nav is not consistent in how it hides/shows navigation items), even though the fix for this issue is included in the theme release that I'm using.
I've nailed it down to that the browser reports the wrong `outerWidth()` of the navigation items some times and thus the `jquery.greedy-navigation.js` logic will compute the wrong thing as the calculations are based on wrong values. From here I've not gotten further though on how/why the browser on some page loads reports the wrong element widths.
Anyways to figure this out I had the need to unminify the main JavaScript file to set some …
> Add instructions on how to unminify main.js for easier browser debugging

- _includes/author-profile-custom-links.html
- _includes/author-profile.html
- _includes/category-list.html
- _includes/page__date.html
- _includes/tag-list.html
- _layouts/single.html
- _sass/minimal-mistakes/_page.scss
Add microformats to markup
See https://github.com/mmistakes/minimal-mistakes/discussions/3017
> Add Microformats

- _sass/minimal-mistakes/_navigation.scss
- _sass/minimal-mistakes/_sidebar.scss
Enable Table of Content sidebar scrolling as mentioned in issue #1851
This can be achieved by simply adding the followings in `_navigation.scss`:
```css
.sidebar__right.sticky > .toc > .toc__menu {
overflow-y: auto;
max-height: calc(100vh - 7em);
}
```
When the toc sidebar is not sticky, this rule will not apply. While if the toc sidebar is sticky (`.sticky`), the `toc_menu`'s height will be limited, and the content will be scrollable with a thin-width scrollbar. I use `max-height` instead of `height` to ensure that short TOCs will not be affected by this rule.
Other scrollbar CSS rules is just for making the scrollbar thin in Chrome/Firefox/... If the default wide scrollbar is not preferred, I can simply remove those style rules and keep the 4 lines …
> Enable toc sidebar scrolling

- _includes/video
include video does not survive compress_html. video contains //--> which confuses compress_html. Changed to -->
Is this related to any GitHub issue(s)? - No
> include video does not survive compress.html

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation.yml
Use [GitHub issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) to direct support questions to Discussions.
You can [preview this PR on my fork](https://github.com/iBug/minimal-mistakes/issues/new/choose). I also recommend revising the templates (descriptions / pre-filled text etc.) before/after merging as I feel they could be improved.
P.S. This description should account for a good portion of support questions posted as issues, so I did some rewording on the bug report template. Also I believe "Documentations" would be better renamed to "Feature Request" or "Suggestions", but I lack the background behind the initial choice of this title, so I left it as-is.
<details> …
> Use GitHub issue templates

- _includes/author-profile.html
Keybase icon was not showing. Looks like it has the wrong class. See https://fontawesome.com/v5.15/icons/keybase?style=brands
> Fix keybase class

- docs/_docs/05-configuration.md
Spotted a small typo while I was reading about the `og_image` [setting](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#open-graph-default-image).
Not related to an issue.
> ✏ fix typo

- docs/_docs/05-configuration.md
Just noticing a missing comma.
> Add missing comma

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/bad-pr.yml
Use a GitHub Actions to close invalid PRs that would have been done manually.
This PR adds two aspects of content:
1. An "identification token" for detection, based on the fact that most (if not all) invalid PRs don't even bother reading the `PULL_REQUEST_TEMPLATE`, let alone properly filling them. This provides us with a nice simple heuristic that should "just work" for 99% of the cases.
This PR adds something at the end of the PR template with the hope that a reasonable user would have removed it should they want to submit some real thing, and checks if the "must remove" content is left intact.
**Update 1**: Shortly after the creation of this PR there came 3314 that included an empty body (the user just deleted everything pre-filled in the input box). …
> Automatically close invalid PRs using GitHub Actions

- _sass/minimal-mistakes/_notices.scss
Uses the color of `.notice--whatever a` for `blockquote.notice--whatever # border-left-color`.
#3068
> Use <a> color for blockquote.notice border

- _sass/minimal-mistakes/_base.scss
- _sass/minimal-mistakes/_page.scss
"Inline code block" styles are currently not applied to `b > code`, `i > code`, `u > code` etc. due to selectors restricting parent elements to a very small set.
I checked the result of an "apparent fix" and only `pre > code` has a bad look, so I came up with `:not(pre) > code` inside `.page__content` and the result is satisfactory.
> Fix inline code style not applied to stylized text

- _config.yml
- assets/js/lunr/lunr-store.js
- docs/_docs/05-configuration.md
This is a documentation change. 
This gives an optional setting to allow lunr to search all pages and not just the ones in the collections.
I also updated the docs to describe how to use it. 
I needed this for my own website and figure I'd port the changes over for everyone since it's extremely useful to have when you need it.
I used a modified version of the suggested changes by @nandahkrishna  https://github.com/mmistakes/minimal-mistakes/issues/1409#issuecomment-569402881 (note: their repo is MIT license)
This addresses #1409
> add optional lunr searching of pages

- assets/js/plugins/jquery.greedy-navigation.js
Update attribution link for GreedyNav
https://github.com/mmistakes/minimal-mistakes/issues/3552
> Update attribution link

- docs/_docs/05-configuration.md
- docs/_docs/10-layouts.md
- docs/_docs/14-helpers.md
Font Awesome has since released v6 and the old `/icons?d=gallery` path has been changed to `/v5/search`. This PR updates such links in the documentation site.
Any plans for the next release? PRs are piling up.
> Update link to Font Awesome gallery

- _layouts/single.html
See commit info.
According to [Liquid docs](https://shopify.github.io/liquid/basics/operators/#order-of-operations), operators are grouped from right to left, so the existing code is evaluated like this:
```ruby
if page.url != "/" and site.breadcrumbs or page.breadcrumbs != false
if page.url != "/" and (site.breadcrumbs or page.breadcrumbs != false)
```
With `page.breadcrumbs` unset, it becomes `null`, so the last part evaluates to `true` for all pages (for an average user), thus unintendedly enabling breadcrumbs.
[Someone commented](https://github.com/mmistakes/minimal-mistakes/commit/65237df377bf224fdfe3ebac05105e14791e49f8#commitcomment-74852556)
> Fix #3096 enabling breadcrumb on all pages

- _includes/browser-upgrade.html
- _layouts/default.html
Since #3042 has been merged, the notice block is also only bloated bytes now.
> Remove IE9 upgrade notice

- _layouts/single.html
#3668 broke the original intent of "allow disabling breadcrumbs on a per-page basis when it's globally enabled (site-enabled)". I didn't realize that `!= false` held this intention.
Unfortunately [the `default` filter](https://shopify.github.io/liquid/filters/default/) doesn't fit this purpose (it eats `null`, `false` and empty strings) so I had to use another conditional. This should make both #3096 and the comment happy.
> Fix #3668 breaking "disable per-page when globally enabled"

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/bad-pr.yml
This is a follow-up for #3313. Apparently there are worse users who simply get confused as their PRs are closed. Improves the auto-comment to be absolutely clear they're in the wrong place.
Also changed the "detection token" to be part of the comment (that hopefully won't come up in a legitimate PR).
> Improve PR close auto-comment message

- _includes/head.html
Upgrade to the newest `fontawesome` package.
Until now the package has been fixed at version `5.0.0` and has thus never received any bugfixes.
By changing the `@5` to `@latest` in the version tag, minimal-mistakes now ships always with the newest up-to-date version.
(Currently, `6.1.1` is the newest)
I am a researcher and therefore active on many research-related social platforms. I needed some icons that were introduced in later `patch-versions` of fontawesome version `5`, so I had to manually overwrite the `head.html` just to get the newest version. I believe that minimal-mistakes should always ship with the newest patch-version, as `5.0.0` is very outdated and does not include any patches that came after.
I am aware that minimal-mistakes should be …
> ⬆️ load latest fontawesome package

- _layouts/categories.html
abundant code
{{ "ABCD" |  slugify }}
abcd
"slugify" filter calls "Utils.slugfy" without "cased" parameter,
which set to "false" default value.
slug.downcase! unless cased
So "downcase" filter following "slugify seems rebundant.
https://github.com/jekyll/jekyll/blob/master/lib/jekyll/filters.rb#L62
https://github.com/jekyll/jekyll/blob/master/lib/jekyll/utils.rb#L202
> Remove redundant downcase from _layouts/categories.html

- assets/js/lunr/lunr-store.js
To avoid getting JS and irrelevant files indexed remove pages where title is null. This gives a much cleaner lunr store with more relevant content.
> Remove JS and other files from search index

- _includes/search/algolia-search-scripts.html
So that Algolia's InstantSearch-related stuff is only loaded from CDN when user clicks on the search icon. Those files add up to 400 KiB and are currently loaded in a blocking way, which has a non-trivial performance impact.
You can inspect the effect on [my website](https://ibug.io/).
> Lazy-load InstantSearch scripts and stylesheets

- _includes/paginator.html
In code `assign first_page_path = ... | replace: 'page:num', '' | ...`, `page:num` is hard-coded. So if `site.paginate_path` doesn't ends with `page:num/` or `page:num`, `first_page_path` will get a wrong value.
The PR tries parsing the last part from `site.paginate_path`, instead of using a hard-coded `page:num`.
The same issue with: https://github.com/mmistakes/minimal-mistakes/pull/2431#issuecomment-598026992
> If `:num` is used alone (instead of `page:num`) then the previous code would generate wrong results. I have `paginate_path: /blog/:num/` in my config and I expect pages to have URLs like `/blog/2/` instead of `/blog/page2/`, which wasn't available before.
The author of  #2413 addressed the issue with Paginate V2. But I'm using GitHub Actions and only V1 is …
> Fix wrong `first_page_path` because of hard-coded `page:num`

- _includes/social-share.html
Removed url encoding of the article link
Linkedin social share button does not seem to be working correctly when an article's URL is encoded (as in `/` replaced with `%2F` etc). I encountered this bug while trying to share my own article hosted on Github Pages. It does not seem to be the case with common websites, for example `https://google.com/` seems to work both raw and encoded.
I didn't find any issue mentioning that bug - but the fix is quick and simple enough to go with the PR right away.
> Fix Linkedin social share link

- _includes/breadcrumbs.html
Non-English characters being url encoded in breadcrumb navigation.
I added url_decode filter in breadcrumb navigation link text to fix that
Tis related to my discussion #3816
> Fix non-English characters being url encoded in breadcrumb

- .github/workflows/bad-pr.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- _includes/page__hero.html
- docs/_docs/10-layouts.md
Found this lying around while doing bde92b6d4aa00209f41de1d855473d779e0c6a2b. Thought I'd just remove it but hesitated for these reasons:
- I'm a fan of [Semantic Versioning](https://semver.org/) and this is a breaking change for existing users.
- [Material for MkDocs](https://squidfunk.github.io/minimal-mistakes/) is another theme that I use extensively, and it's doing a great job of following SemVer.
- Too minor a change for bumping the "major" version (i.e. v5.0.0).
- As far as I understand, a website theme is intended as a "root dependency" (facing end users directly), so there was no plan to follow SemVer from the beginning. The "major" version of this project is thus intended as "major overhauls" or "reincarnations (not really)".
Context:
- Already deprecated since …
> Remove deprecated "page.header.cta_url" setting

- docs/_docs/10-layouts.md
Update social sharing section for appropriate Reddit example and resource locations.
Could use a second set of eyes. Open to edits. 
Related to Issue #1656 and pull request #1657
> Update Social Sharing links section

- .gitignore
- _includes/masthead.html
- docs/_docs/07-navigation.md
This PR adds `target` attribute for links in the navigation menu.
P.S. I think may be add `attributes` property for more flexible configuration these link?
> Feature: Add target attribute for navigation link

- assets/js/plugins/jquery.greedy-navigation.js
The pop up menu above disappears after you move the cursor out of it. However, the white overlay on the screen does not disappear, as well as the x nav button on the top-right, remains as is.
Now when you click anywhere on the screen, the popup appears again, and the x nav button turns back to a hamburger menu button.
And when you click on the hamburger menu, the popup disappears.
The functionality is now behaving in the exact opposite that we want to.
To remedy this, once the popup disappears the x nav button should also return back to normal (hamburger button)
This commit fixes this issue.
This is a direct pull request. No related Github issue
> Remove overlay and revert X to hamburger icon when popup disappears

- _includes/archive-single.html
- _includes/breadcrumbs.html
- _layouts/archive-taxonomy.html
- _layouts/archive.html
- _layouts/default.html
- _layouts/search.html
- _layouts/single.html
- _layouts/splash.html
This is a feature. 
This PR allows for a page to specify a content `locale` that is used only for _that one_ page.
Compared to the similar PR https://github.com/mmistakes/minimal-mistakes/pull/4679,  this set of changes is relatively small, as I am not going for localising anything. Instead, the focus is on expressing the _actual_ locale of the content, as it is written in the page and declared as `locale` in the front matter, in the containing element's `lang` attribute.
Fallback to `site.locale` is present where applicable.
This PR has an associated commit that writes the site locale (`lang` attribute of the `html` element) in the style the W3C recommends (language and region separated by dash), instead of just cutting off the region. Let me know if you'd prefer this one as a separate …
> Page locale

- _includes/head.html
The `<script>` in `_includes/head.html` had a `type=text/javascript` attribute which was unnecessary and gives a warning in an HTML validator.
This pull request removes that.
Valid HTML is always a good idea :-)
> Remove unnecessary "type" attribute

- _includes/social-share.html
Fixes the social share include so the default text works as expected.
The current code looks like this:
{% if site.data.ui-text[site.locale].share_on_label %}
<h4 class="page__share-title">{{ site.data.ui-text[site.locale].share_on_label | default: "Share on" }}</h4>
{% endif %}
The `if` statement means that the default ("Share on") is never used. And I assume that's what most people would want to see.
Also, without the `<h4>`, we get a HTML validation warning - as the `<section class="page__share">` has no header.
Just removing the `if`/`endif` lines fixes these problems without changing the behaviour.
> The "if" means the default is never used

- _includes/seo.html
This pull request addresses the issue of duplicated titles in the SEO metadata. The fix involves overriding the seo.html file and     updating the logic to ensure the page title doesn't include the site title twice. The change ensures that the title displayed in the     browser tab and metadata is clean and correctly formatted.
Changes Include:
- Created a custom _includes/seo.html file.
- Updated the logic in seo.html to prevent the page title from containing the site title twice.
Testing:
- Verified that the title is no longer duplicated in the browser tab and in the generated HTML meta tags.
> Fix: Prevent double title issue in SEO metadata by updating seo.html

- assets/js/plugins/jquery.greedy-navigation.js
When a "hidden" nav bar link is clicked in a mobile view, the overlay doesn't go away. You'll only notice if the link is to an on-page location.
See [this video](https://www.loom.com/share/987f39548b7443f3a1df903f472f8849?sid=f7684184-c1d5-4cbb-895f-3ff06087afbf) for a walkthrough of the issue and an easy front-end fix. The script in the fix looks like this:
```js
$(function () {
var $btn = $("nav.greedy-nav .greedy-nav__toggle");
var $hlinks = $("nav.greedy-nav .hidden-links");
// Window listeners
$hlinks.on("click", function () {
$hlinks.addClass("hidden");
$btn.removeClass("close");
});
});
```
This PR applies the fix directly to the plugin code.
See issue #4537
> Hide hidden links & remove the overlay when one is clicked

- _layouts/single.html
- Enhanced the comments section logic in `single.html` to provide detailed feedback during development.
- Displays the current comments provider and configuration status when running in a non-production environment.
- Added fallback messages for scenarios where comments are disabled or no provider is specified.
- Ensures clarity for debugging comments setup without affecting production behavior.
- Tested thoroughly to confirm:
1. Proper display of provider and configuration in non-production environments.
2. Production environment behavior remains unaffected.
3. Comprehensive handling of cases with missing or disabled comments.
Enhanced the comments section in `single.html` to display provider and configuration details during development. This provides …
> feat(single.html): Add provider and comments info for non-production

- docs/_docs/05-configuration.md
Fixes a typo I found while reading through the docs.
Is this related to any GitHub issue(s)?
-> No
> Fix typo in docs/_docs/05-configuration.md

- _sass/minimal-mistakes/_buttons.scss
This is a bug fix
Add mastodon-color to the buttons scss file. The color code is already present, just not defined as a button.
I'm working on adding a 'share to mastodon' and was looking for the right colors.
> Mastodon button color

- _sass/minimal-mistakes/skins/_contrast.scss
The current $primary-color red (#ff0000) fails the WCAG requirements because it does not have sufficient contrast when used on buttons. Using slightly darker red (#b60000) does pass.
Resolves #5122.
> Tweak contrast skin $primary-color to adhere to WCAG guidelines

- _includes/social-share.html
**Title**: 
**Description**:
- Replaced the Twitter share button URL from `twitter.com` to `x.com`, reflecting Twitter's rebranding to X.
- Updated the button class from `btn--twitter` to `btn--x` for consistency with the new branding.
- Modified the icon class for the X button to use `fa-share-alt` for better representation.
- Ensured that all relevant social media platforms (Facebook, LinkedIn, X) now have updated buttons.
- The change will allow users to share content on the new X platform instead of Twitter.
**Reason for Change**:
- As part of the ongoing rebranding of Twitter to X, the social sharing links need to be updated to maintain proper functionality for users sharing content to X.
- Ensures the website remains up-to-date with the latest social media changes.
**Notes**:
- This …
> Update Social Share Buttons to Reflect Twitter Rebranding to X

- _sass/minimal-mistakes/_base.scss
- _sass/minimal-mistakes/_variables.scss
Provided in variables are now modern font stacks which can easily be used to switch the font of the site.
Added the font definitions from the modern font stack to be able to quickly switch fonts if desired.
> Modern font stack

- CHANGELOG.md
- _includes/footer.html
Hide page__footer-follow if there are no links nor atom feed. This prevents showing the FOLLOW label without any content next to it.
n/a
> Hide page__footer-follow if there are no links nor atom feed.

- _sass/minimal-mistakes/_notices.scss
This adds built-in support for the [`jekyll-gfm-admonitions` plugin by Helveg](https://github.com/Helveg/jekyll-gfm-admonitions/) to the Minimal Mistakes theme.  The plugin adds formatting for GFM admonitions (called ["Alerts" in GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)) to match the styling used in notice blocks.
> Add built-in support for jekyll-gfm-admonitions
